name = "hello_world"
description = "hello world"
version = "0.1.0-dev"

authors = ["Matheus Nielsen"]
maintainers = ["Matheus Nielsen <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
